# Generated by Django 3.1.7 on 2021-03-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateTimeField(verbose_name='%d-%m-%Y %H:%M:%S'),
        ),
    ]
